stages:
  - build
  - deploy

pages:
  stage: build
  image: bitnami/node
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - node_modules/
  script:
    - npm install
    - npm run build
  artifacts:
    expire_in: 30min
    paths:
      - public
  only:
    - main
