name: Check Missing Languages

on:
  push:
    paths:
      - "missing-i18n.json"
  workflow_dispatch:

jobs:
  check-langs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install @actions/core @actions/github

      - name: Run language check script
        run: node scripts/checkLangs.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
